// <auto-generated />
using System;
using ComplianceWala.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComplianceWala.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ComplianceWala.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BuyerGstin")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("buyer_gstin");

                    b.Property<decimal>("Cgst")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("cgst");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Igst")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("igst");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsFromPurchaseRegister")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_from_purchase_register");

                    b.Property<Guid?>("ReconciliationSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReconciliationSessionId1")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sgst")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("sgst");

                    b.Property<string>("SupplierGstin")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_gstin");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_name");

                    b.Property<decimal>("TaxableValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("taxable_value");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .HasDatabaseName("ix_invoices_invoice_number");

                    b.HasIndex("ReconciliationSessionId");

                    b.HasIndex("ReconciliationSessionId1");

                    b.HasIndex("SupplierGstin")
                        .HasDatabaseName("ix_invoices_supplier_gstin");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("ComplianceWala.Domain.Entities.MismatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("AiConfidenceScore")
                        .HasPrecision(4, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_confidence_score");

                    b.Property<string>("AiExplanation")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_explanation");

                    b.Property<string>("AiExplanationHindi")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_explanation_hindi");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_at");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_resolved");

                    b.Property<decimal>("ItcAmountAtRisk")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("itc_amount_at_risk");

                    b.Property<int>("MismatchType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mismatch_type");

                    b.Property<Guid>("ReconciliationSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reconciliation_session_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("gstr2b_invoice_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("purchase_register_invoice_id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MismatchType")
                        .HasDatabaseName("ix_mismatch_records_type");

                    b.HasIndex("ReconciliationSessionId")
                        .HasDatabaseName("ix_mismatch_records_session_id");

                    b.HasIndex("gstr2b_invoice_id");

                    b.HasIndex("purchase_register_invoice_id");

                    b.ToTable("mismatch_records", (string)null);
                });

            modelBuilder.Entity("ComplianceWala.Domain.Entities.ReconciliationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessGstin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilingPeriod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReconciliationSessions");
                });

            modelBuilder.Entity("ComplianceWala.Domain.Entities.SupplierProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Gstin")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("gstin");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("_filingHistory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("filing_history");

                    b.HasKey("Id");

                    b.HasIndex("Gstin")
                        .IsUnique()
                        .HasDatabaseName("ix_supplier_profiles_gstin");

                    b.ToTable("supplier_profiles", (string)null);
                });

            modelBuilder.Entity("ComplianceWala.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("ComplianceWala.Domain.Entities.ReconciliationSession", null)
                        .WithMany("Gstr2bInvoices")
                        .HasForeignKey("ReconciliationSessionId");

                    b.HasOne("ComplianceWala.Domain.Entities.ReconciliationSession", null)
                        .WithMany("PurchaseRegisterInvoices")
                        .HasForeignKey("ReconciliationSessionId1");
                });

            modelBuilder.Entity("ComplianceWala.Domain.Entities.MismatchRecord", b =>
                {
                    b.HasOne("ComplianceWala.Domain.Entities.ReconciliationSession", null)
                        .WithMany("Mismatches")
                        .HasForeignKey("ReconciliationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplianceWala.Domain.Entities.Invoice", "Gstr2bInvoice")
                        .WithMany()
                        .HasForeignKey("gstr2b_invoice_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ComplianceWala.Domain.Entities.Invoice", "PurchaseRegisterInvoice")
                        .WithMany()
                        .HasForeignKey("purchase_register_invoice_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("ComplianceWala.Domain.ValueObjects.ItcRiskScore", "RiskScore", b1 =>
                        {
                            b1.Property<Guid>("MismatchRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("AmountAtRisk")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("risk_score_amount");

                            b1.Property<decimal>("BlockingProbability")
                                .HasPrecision(4, 3)
                                .HasColumnType("TEXT")
                                .HasColumnName("risk_score_probability");

                            b1.Property<int>("Level")
                                .HasColumnType("INTEGER")
                                .HasColumnName("risk_score_level");

                            b1.HasKey("MismatchRecordId");

                            b1.ToTable("mismatch_records");

                            b1.WithOwner()
                                .HasForeignKey("MismatchRecordId");
                        });

                    b.Navigation("Gstr2bInvoice");

                    b.Navigation("PurchaseRegisterInvoice");

                    b.Navigation("RiskScore")
                        .IsRequired();
                });

            modelBuilder.Entity("ComplianceWala.Domain.Entities.ReconciliationSession", b =>
                {
                    b.Navigation("Gstr2bInvoices");

                    b.Navigation("Mismatches");

                    b.Navigation("PurchaseRegisterInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
