using ComplianceWala.Domain.Enums;
using ComplianceWala.Domain.Exceptions;
using ComplianceWala.Domain.ValueObjects;

namespace ComplianceWala.Domain.Entities;

/// <summary>
/// Represents one detected discrepancy between a buyer's purchase register
/// and the government's GSTR-2B statement.
/// 
/// Each MismatchRecord is the OUTPUT of our reconciliation engine.
/// It contains: what's different, why it's different, how much ITC is at risk,
/// and an AI-generated explanation in plain language.
/// </summary>
public class MismatchRecord
{
    public Guid Id { get; private set; }

    /// <summary>Which reconciliation session this mismatch belongs to.</summary>
    public Guid ReconciliationSessionId { get; private set; }

    // ── The Two Sides of the Mismatch ─────────────────────────────
    
    /// <summary>
    /// Invoice from buyer's purchase register (may be null if invoice 
    /// exists in GSTR-2B but not in buyer's books — rare but valid).
    /// </summary>
    public Invoice? PurchaseRegisterInvoice { get; private set; }

    /// <summary>
    /// Invoice from GSTR-2B (may be null if invoice is in buyer's books 
    /// but supplier never filed — the most common mismatch).
    /// </summary>
    public Invoice? Gstr2bInvoice { get; private set; }

    // ── Classification ────────────────────────────────────────────
    
    public MismatchType MismatchType { get; private set; }

    /// <summary>ITC amount at stake in this specific mismatch.</summary>
    public decimal ItcAmountAtRisk { get; private set; }

    public ItcRiskScore RiskScore { get; private set; } = null;

    // ── AI-Generated Explanation ──────────────────────────────────
    
    /// <summary>
    /// Plain English explanation generated by our LLM layer (Day 10-11).
    /// Initially empty — populated after AI processing.
    /// Example: "Your supplier ABC Traders hasn't filed their March GSTR-1.
    /// Your ₹42,000 ITC is at risk. Contact them before November 30."
    /// </summary>
    public string? AiExplanation { get; private set; }

    /// <summary>
    /// Same explanation in Hindi — generated by LLM.
    /// </summary>
    public string? AiExplanationHindi { get; private set; }

    /// <summary>How confident the AI is in its classification (0.0 to 1.0).</summary>
    public decimal AiConfidenceScore { get; private set; }

    public bool IsResolved { get; private set; }
    public DateTime DetectedAt { get; private set; }
    public DateTime? ResolvedAt { get; private set; }

    // ── Constructor ───────────────────────────────────────────────
    
    private MismatchRecord() { }

    public static MismatchRecord Detect(
        Guid reconciliationSessionId,
        MismatchType mismatchType,
        decimal itcAmountAtRisk,
        ItcRiskScore riskScore,
        Invoice? purchaseRegisterInvoice = null,
        Invoice? gstr2bInvoice = null)
    {
        // At least one invoice must exist — a mismatch needs something to compare
        if (purchaseRegisterInvoice is null && gstr2bInvoice is null)
            throw new DomainException("INVALID_MISMATCH",
                "A mismatch record must reference at least one invoice.");

        if (itcAmountAtRisk < 0)
            throw new DomainException("NEGATIVE_ITC",
                "ITC amount at risk cannot be negative.");

        return new MismatchRecord
        {
            Id = Guid.NewGuid(),
            ReconciliationSessionId = reconciliationSessionId,
            MismatchType = mismatchType,
            ItcAmountAtRisk = itcAmountAtRisk,
            RiskScore = riskScore,
            PurchaseRegisterInvoice = purchaseRegisterInvoice,
            Gstr2bInvoice = gstr2bInvoice,
            IsResolved = false,
            DetectedAt = DateTime.UtcNow,
            AiConfidenceScore = 0m  // Populated later by AI layer
        };
    }

    // ── Behavior Methods ──────────────────────────────────────────
    
    /// <summary>
    /// Called by the AI service layer (Day 10) to attach generated explanations.
    /// </summary>
    public void AttachAiExplanation(
        string explanationEnglish,
        string explanationHindi,
        decimal confidenceScore)
    {
        if (confidenceScore < 0 || confidenceScore > 1)
            throw new DomainException("INVALID_CONFIDENCE",
                $"AI confidence must be between 0 and 1. Received: {confidenceScore}");

        AiExplanation = explanationEnglish;
        AiExplanationHindi = explanationHindi;
        AiConfidenceScore = confidenceScore;
    }

    /// <summary>Marks this mismatch as resolved by the user.</summary>
    public void MarkResolved()
    {
        if (IsResolved)
            throw new DomainException("ALREADY_RESOLVED",
                $"Mismatch {Id} is already marked as resolved.");

        IsResolved = true;
        ResolvedAt = DateTime.UtcNow;
    }
}